name: Apply Branch Protection Org-Wide

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to protect'
        required: true
        default: 'main' # Default branch if none provided

permissions:
  contents: read
  actions: write

jobs:
  set-branch-protection:
    runs-on: ubuntu-latest
    steps:
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get List of Repositories
        id: repos
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_PAT_TOKEN }}  # Use your PAT here
        run: |
          repos=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/orgs/${{ github.repository_owner }}/repos?per_page=100 \
              | jq -r '.[].name')
          echo "::set-output name=repos::$repos"

      - name: Apply Branch Protection to Each Repo
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_PAT_TOKEN }}  # Use your PAT here
        run: |
          branch="${{ github.event.inputs.branch }}"
          for repo in ${{ steps.repos.outputs.repos }}; do
            echo "Applying branch protection to repository: $repo on branch: $branch"
            curl -X PUT \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.luke-cage-preview+json" \
              https://api.github.com/repos/${{ github.repository_owner }}/$repo/branches/$branch/protection \
              -d '{
                  "required_status_checks": {
                    "strict": true,
                    "contexts": ["ci/test"]
                  },
                  "enforce_admins": false,
                  "required_pull_request_reviews": {
                    "dismiss_stale_reviews": true,
                    "require_code_owner_reviews": true,
                    "required_approving_review_count": 2
                  },
                  "restrictions": null
              }'
          done
